# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. 
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme

url    : "https://brightplum.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog

title      : Drupal Web Development Experts | Bright Plum, Inc. | Chicago, Dallas, Greensboro
email      : fredric@brightplum.com #this is also the email contact forms will go to
description: "Bright Plum, Inc. is a micro-agency specializing in web platform development using Drupal."
author     : Fredric Mitchell
logo:     #optional, defaults to site title
  path: https://res.cloudinary.com/brightplum/image/upload/v1602789644/brightplum/brightplum_logo.png
  # height: 60 #height in px, defaults to 52px

formspree_form_path: https://formspree.io/f/xdopeyol

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

plugins:
  - jekyll-remote-theme
